// Forty Days in His Words: the journal's text. Every `text` is exact KJV
// (1769) as spoken by Jesus; build.js checks each one against
// data/gospels-kjv.json and refuses to build if a word differs.
// "…" joins two of his lines in the same passage; the verse range covers both.

module.exports = {
  title: 'Forty Days in His Words',
  subtitle: 'A Lent journal in the words Jesus spoke',
  year: 2027,
  ashWednesday: '2027-02-10',
  easterDate: '2027-03-28',
  weeks: [
    { name: 'Turn', note: 'Ash Wednesday to Saturday. Lent begins where his preaching began: with an invitation to turn around.' },
    { name: 'The Blessed', note: 'The first week walks through the Sermon on the Mount, where he tells ordinary people who is blessed and how to pray.' },
    { name: 'The Hard Command', note: 'This week holds the sayings most of us would rather skip: love, forgive, do not judge.' },
    { name: 'The Stories He Told', note: 'A week of parables. Read each one as a story first and a lesson second.' },
    { name: 'In the Storm', note: 'Words he spoke to frightened, sick and accused people, often in a single sentence.' },
    { name: 'I Am', note: 'In John he names himself in pictures: bread, light, shepherd, door, vine.' },
    { name: 'Holy Week', note: 'From the road into Jerusalem to the cross. These are his last words before the silence of Saturday.' },
  ],
  days: [
    // Turn
    { week: 0, title: 'The time is now', cite: 'Mark 1:15', text: 'The time is fulfilled, and the kingdom of God is at hand: repent ye, and believe the gospel.',
      reflection: 'These are the first words Mark records him saying. To repent is to turn around, to face a new direction. He puts it next to good news on purpose: you are not turning toward a punishment, you are turning toward something near and good. Lent is forty days of practicing that turn.',
      question: 'What would you like to turn away from, and what would you like to turn toward, by Easter?' },
    { week: 0, title: 'Follow me', cite: 'Matthew 4:19', text: 'Follow me, and I will make you fishers of men.',
      reflection: 'He said this to two working men standing in their boats. He did not ask them to understand everything first, or to become someone else before they started. He asked them to walk behind him, and promised that he would do the making.',
      question: 'Where in your ordinary day could you follow him more closely this week?' },
    { week: 0, title: 'Not by bread alone', cite: 'Matthew 4:4', text: 'It is written, Man shall not live by bread alone, but by every word that proceedeth out of the mouth of God.',
      reflection: 'He was hungry when he said it, forty days into the wilderness. Lent copies those forty days. Whatever you have set aside this season, the empty space it leaves is room to be fed another way.',
      question: 'What are you fasting from, and what would you like to fill that space with?' },
    { week: 0, title: 'Come unto me', cite: 'Matthew 11:28–30', text: 'Come unto me, all ye that labour and are heavy laden, and I will give you rest. Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls. For my yoke is easy, and my burden is light.',
      reflection: 'A yoke is what lets an animal pull a load without being crushed by it. He does not offer a life with no load. He offers to share it, and describes himself, for once, in two plain words: meek and lowly.',
      question: 'What are you carrying into this Lent that you would like to set down?' },

    // The Blessed
    { week: 1, title: 'Blessed are the poor in spirit', cite: 'Matthew 5:3–4', text: 'Blessed are the poor in spirit: for theirs is the kingdom of heaven. Blessed are they that mourn: for they shall be comforted.',
      reflection: 'He begins his longest sermon with the people who have least to show. The poor in spirit are the ones who know they cannot manage alone. The mourning are promised comfort, not a lecture. Notice who he blesses first.',
      question: 'Where do you feel poor in spirit right now? What would comfort look like there?' },
    { week: 1, title: 'The merciful and the peacemakers', cite: 'Matthew 5:7–9', text: 'Blessed are the merciful: for they shall obtain mercy. Blessed are the pure in heart: for they shall see God. Blessed are the peacemakers: for they shall be called the children of God.',
      reflection: 'Mercy given and mercy received belong together in this sentence. Peacemakers are not people who avoid conflict. They make peace, which is work, and he gives them the family name.',
      question: 'Who needs mercy from you this week? Where could you make peace?' },
    { week: 1, title: 'Let your light shine', cite: 'Matthew 5:14–16', text: 'Ye are the light of the world. A city that is set on an hill cannot be hid. Neither do men light a candle, and put it under a bushel, but on a candlestick; and it giveth light unto all that are in the house. Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.',
      reflection: 'He does not say "try to become light." He says "ye are." The question is only where the lamp sits. A light under a basket is still a light; it just helps no one in the house.',
      question: 'What small good work could you do today that would help someone in your house?' },
    { week: 1, title: 'Pray in secret', cite: 'Matthew 6:6', text: 'But thou, when thou prayest, enter into thy closet, and when thou hast shut thy door, pray to thy Father which is in secret; and thy Father which seeth in secret shall reward thee openly.',
      reflection: 'Prayer, in his telling, needs a door you can close. No audience, no performance. The Father he describes is already in the secret place waiting.',
      question: 'Where and when could you find a closed door this week, even for five minutes?' },
    { week: 1, title: 'After this manner pray', cite: 'Matthew 6:9–13', text: 'After this manner therefore pray ye: Our Father which art in heaven, Hallowed be thy name. Thy kingdom come. Thy will be done in earth, as it is in heaven. Give us this day our daily bread. And forgive us our debts, as we forgive our debtors. And lead us not into temptation, but deliver us from evil: For thine is the kingdom, and the power, and the glory, for ever. Amen.',
      reflection: 'Pray it slowly today, one line at a time, and stop at the line that catches. It asks for bread for today, not for the year. It ties our own forgiveness to the forgiving we do.',
      question: 'Which line of the prayer stopped you? Write about why.' },
    { week: 1, title: 'Seek first', cite: 'Matthew 6:33–34', text: 'But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you. Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself. Sufficient unto the day is the evil thereof.',
      reflection: 'He is honest that each day has its own trouble. He simply refuses to let tomorrow’s trouble move into today. Seeking the kingdom first is an order of attention, not a list of extra duties.',
      question: 'What worry about tomorrow could you hand back today?' },

    // The Hard Command
    { week: 2, title: 'Love your enemies', cite: 'Matthew 5:44', text: 'But I say unto you, Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you, and persecute you;',
      reflection: 'This is the hardest sentence in the Sermon, and he says it plainly. Love here is a set of actions: bless, do good, pray. It does not ask you to pretend harm was not done. It asks you not to let it make you into someone who harms back.',
      question: 'Is there someone you could pray for today whom you would rather not?' },
    { week: 2, title: 'Judge not', cite: 'Matthew 7:1–2', text: 'Judge not, that ye be not judged. For with what judgment ye judge, ye shall be judged: and with what measure ye mete, it shall be measured to you again.',
      reflection: 'The measure you use on others is the one you will live under. Most of us are quicker to measure others than to notice the scale we are carrying.',
      question: 'Whom have you been measuring harshly? What would a gentler measure sound like?' },
    { week: 2, title: 'The mote and the beam', cite: 'Matthew 7:3', text: 'And why beholdest thou the mote that is in thy brother’s eye, but considerest not the beam that is in thine own eye?',
      reflection: 'A speck of sawdust and a wooden beam. He uses a carpenter’s joke to say something serious: it is easier to see small faults in others than large ones in ourselves.',
      question: 'What beam might you have been overlooking in your own eye?' },
    { week: 2, title: 'Seventy times seven', cite: 'Matthew 18:22', text: 'I say not unto thee, Until seven times: but, Until seventy times seven.',
      reflection: 'Peter offered seven, which was generous. He answers with a number meant to stop the counting altogether. Forgiveness is not a ledger that eventually runs out.',
      question: 'Is there a forgiveness you keep starting over? Write about where you are in it today.' },
    { week: 2, title: 'Give', cite: 'Luke 6:38', text: 'Give, and it shall be given unto you; good measure, pressed down, and shaken together, and running over, shall men give into your bosom. For with the same measure that ye mete withal it shall be measured to you again.',
      reflection: 'He describes grain being poured into a fold of a robe: pressed down, shaken so it settles, poured until it spills over. Generosity, in his picture, comes back the same way it goes out.',
      question: 'What could you give away this week: time, money, attention, an apology?' },
    { week: 2, title: 'A new commandment', cite: 'John 13:34–35', text: 'A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another. By this shall all men know that ye are my disciples, if ye have love one to another.',
      reflection: 'He said this at supper on his last night. The mark of his followers is not a belief or a badge. It is visible love, the kind other people notice.',
      question: 'How would someone watching your week know whom you follow?' },

    // The Stories He Told
    { week: 3, title: 'The lost sheep', cite: 'Luke 15:4', text: 'What man of you, having an hundred sheep, if he lose one of them, doth not leave the ninety and nine in the wilderness, and go after that which is lost, until he find it?',
      reflection: 'He asks it as if the answer is obvious, though it is not. Leaving ninety-nine to find one is not efficient. It is love that counts by name rather than by percentage.',
      question: 'When have you been the one he came looking for? When have you been sent to look?' },
    { week: 3, title: 'A great way off', cite: 'Luke 15:20', text: 'And he arose, and came to his father. But when he was yet a great way off, his father saw him, and had compassion, and ran, and fell on his neck, and kissed him.',
      reflection: 'In the story he told, the son has a speech prepared. The father does not wait to hear it. He sees him from far away, which means he was watching the road, and he runs.',
      question: 'What speech have you rehearsed for God? What if you were met before you finished it?' },
    { week: 3, title: 'The mustard seed', cite: 'Matthew 13:31–32', text: 'The kingdom of heaven is like to a grain of mustard seed, which a man took, and sowed in his field: Which indeed is the least of all seeds: but when it is grown, it is the greatest among herbs, and becometh a tree, so that the birds of the air come and lodge in the branches thereof.',
      reflection: 'The smallest seed becomes a place where birds can rest. His kingdom starts small and grows into shelter for others. Small faithful things count.',
      question: 'What small thing could you plant this week that might shelter someone later?' },
    { week: 3, title: 'The Samaritan', cite: 'Luke 10:33–34', text: 'But a certain Samaritan, as he journeyed, came where he was: and when he saw him, he had compassion on him, And went to him, and bound up his wounds, pouring in oil and wine, and set him on his own beast, and brought him to an inn, and took care of him.',
      reflection: 'Count the verbs: saw, had compassion, went, bound, poured, set, brought, took care. The hero of the story is the outsider his listeners least expected. Compassion, here, is something you do with your hands.',
      question: 'Who is lying by the side of your road? What is one verb you could act on?' },
    { week: 3, title: 'The pearl of great price', cite: 'Matthew 13:45–46', text: 'Again, the kingdom of heaven is like unto a merchant man, seeking goodly pearls: Who, when he had found one pearl of great price, went and sold all that he had, and bought it.',
      reflection: 'The merchant is not sad about selling everything. He has found something worth more. Lent’s giving up is meant to feel like that trade, not like loss.',
      question: 'What has been crowding out the one thing you most value?' },
    { week: 3, title: 'God be merciful to me', cite: 'Luke 18:13–14', text: 'And the publican, standing afar off, would not lift up so much as his eyes unto heaven, but smote upon his breast, saying, God be merciful to me a sinner. I tell you, this man went down to his house justified rather than the other: for every one that exalteth himself shall be abased; and he that humbleth himself shall be exalted.',
      reflection: 'The tax collector’s whole prayer is seven words. He says he went home made right. Honesty about ourselves is the doorway, not the obstacle.',
      question: 'Write your own seven-word prayer for today.' },

    // In the Storm
    { week: 4, title: 'Peace, be still', cite: 'Mark 4:39–40', text: 'Peace, be still. … Why are ye so fearful? how is it that ye have no faith?',
      reflection: 'He speaks three words to the wind and then a question to his friends. The storm obeyed first. His question is not a scolding so much as an invitation to notice who is in the boat.',
      question: 'What storm is loud in your life right now? What would it mean to hear "be still" inside it?' },
    { week: 4, title: 'It is I', cite: 'Matthew 14:27', text: 'Be of good cheer; it is I; be not afraid.',
      reflection: 'They thought he was a ghost. He answers with his own presence before he answers anything else. Courage starts with knowing who has come to you on the water.',
      question: 'Where do you need to hear "it is I" this week?' },
    { week: 4, title: 'Go in peace', cite: 'Mark 5:34', text: 'Daughter, thy faith hath made thee whole; go in peace, and be whole of thy plague.',
      reflection: 'She had been ill for twelve years and only meant to touch his clothes and slip away. He stopped the crowd to find her, called her daughter, and sent her home whole. He did not want her healing to stay hidden.',
      question: 'What have you been trying to bring to him quietly, hoping no one notices?' },
    { week: 4, title: 'All things are possible', cite: 'Mark 9:23', text: 'If thou canst believe, all things are possible to him that believeth.',
      reflection: 'The father who heard this answered with one of the most honest prayers in the Gospels: "Lord, I believe; help thou mine unbelief." He was not turned away for mixed faith. Mixed faith is still faith.',
      question: 'Where is your belief mixed with doubt? Pray the father’s prayer about it.' },
    { week: 4, title: 'Faith as a grain of mustard seed', cite: 'Matthew 17:20', text: 'Because of your unbelief: for verily I say unto you, If ye have faith as a grain of mustard seed, ye shall say unto this mountain, Remove hence to yonder place; and it shall remove; and nothing shall be impossible unto you.',
      reflection: 'The mustard seed again. He does not ask for a large faith. He asks for a real one, however small, aimed at a real mountain.',
      question: 'Name one mountain in your life. What would small, real faith do about it this week?' },
    { week: 4, title: 'Neither do I condemn thee', cite: 'John 8:10–11', text: 'Woman, where are those thine accusers? hath no man condemned thee? … Neither do I condemn thee: go, and sin no more.',
      reflection: 'Everyone with a stone has gone. The only one left who could throw it refuses. Then he sends her into a new life. The order matters: mercy first, then the new way.',
      question: 'What accusation have you been carrying? Hear his answer, and write what comes next.' },

    // I Am
    { week: 5, title: 'The bread of life', cite: 'John 6:35', text: 'I am the bread of life: he that cometh to me shall never hunger; and he that believeth on me shall never thirst.',
      reflection: 'The day after he fed five thousand, he told the crowd that he himself was the bread. Bread is ordinary and daily. He offers himself the same way.',
      question: 'What are you hungry for that ordinary bread cannot satisfy?' },
    { week: 5, title: 'The light of the world', cite: 'John 8:12', text: 'I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life.',
      reflection: 'He does not promise the night will disappear. He promises that the one who follows will not walk in it. A lamp lights the next step, which is usually all we need.',
      question: 'What is the next step you can see by his light?' },
    { week: 5, title: 'The good shepherd', cite: 'John 10:11', text: 'I am the good shepherd: the good shepherd giveth his life for the sheep.',
      reflection: 'A hired hand runs when the wolf comes. The good shepherd stays, at his own cost. Holy Week is two weeks away; this sentence points toward it.',
      question: 'When have you felt shepherded? When have you been asked to shepherd someone else?' },
    { week: 5, title: 'The resurrection and the life', cite: 'John 11:25–26', text: 'I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live: And whosoever liveth and believeth in me shall never die. Believest thou this?',
      reflection: 'He said this to Martha, whose brother had been dead four days, before he raised him. Then he asked her a direct question. He asks it of every reader, too.',
      question: 'How would you answer his question today, honestly?' },
    { week: 5, title: 'The way, the truth, and the life', cite: 'John 14:6', text: 'I am the way, the truth, and the life: no man cometh unto the Father, but by me.',
      reflection: 'Thomas had just said, "we know not whither thou goest; and how can we know the way?" He answers that the way is a person to walk with, not only a map to memorize.',
      question: 'Where are you unsure of the way right now? Write it as Thomas might have asked it.' },
    { week: 5, title: 'The vine', cite: 'John 15:5', text: 'I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit: for without me ye can do nothing.',
      reflection: 'Branches do not strain to make grapes. They stay attached and the fruit comes. Abide means remain, stay put, keep living there.',
      question: 'What helps you stay connected to him? What tends to cut you off?' },

    // Holy Week
    { week: 6, title: 'A corn of wheat', cite: 'John 12:24', text: 'Verily, verily, I say unto you, Except a corn of wheat fall into the ground and die, it abideth alone: but if it die, it bringeth forth much fruit.',
      reflection: 'He said this after entering Jerusalem, when visitors were asking to see him. He was speaking of his own death and of the harvest that would follow it. Some things only grow by being let go.',
      question: 'What might need to fall into the ground in you so that something new can grow?' },
    { week: 6, title: 'Wash one another’s feet', cite: 'John 13:14–15', text: 'If I then, your Lord and Master, have washed your feet; ye also ought to wash one another’s feet. For I have given you an example, that ye should do as I have done to you.',
      reflection: 'Foot washing was a servant’s job. He took the towel himself, then told them to do the same for each other. The example is humble service, done in person.',
      question: 'Whose feet could you wash this week, in whatever form that takes?' },
    { week: 6, title: 'My peace I give unto you', cite: 'John 14:27', text: 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.',
      reflection: 'He gave this on the night he was betrayed, knowing what the next day held. His peace is not the absence of trouble. It is something he leaves with us inside it.',
      question: 'Where is your heart troubled? Receive his peace there, and write about it.' },
    { week: 6, title: 'Not as I will', cite: 'Matthew 26:39', text: 'O my Father, if it be possible, let this cup pass from me: nevertheless not as I will, but as thou wilt.',
      reflection: 'Maundy Thursday night in the garden. He asks honestly for another way. Then he trusts his Father with the answer. Both halves of this prayer are allowed.',
      question: 'Pray both halves of his prayer about something you are facing.' },
    { week: 6, title: 'It is finished', cite: 'John 19:30', text: 'It is finished:', display: 'It is finished.',
      reflection: 'Good Friday. In the Greek it is one word, used on receipts to mean "paid in full." Read his seven last words on the facing page slowly today. Nothing more is needed from you than to stay near the cross.',
      question: 'Which of his seven last words stays with you today?', sevenWords: true },
    { week: 6, title: 'Into thy hands', cite: 'Luke 23:46', text: 'Father, into thy hands I commend my spirit:', display: 'Father, into thy hands I commend my spirit.',
      reflection: 'Holy Saturday is the quiet day. His last words were a prayer of trust, a line from Psalm 31 that he would have learned as a child. Today is for waiting, the way his friends waited.',
      question: 'What are you waiting for? Commend it into the Father’s hands.' },
  ],
  sevenWords: [
    { cite: 'Luke 23:34', text: 'Father, forgive them; for they know not what they do.' },
    { cite: 'Luke 23:43', text: 'Verily I say unto thee, To day shalt thou be with me in paradise.' },
    { cite: 'John 19:26–27', text: 'Woman, behold thy son! … Behold thy mother!' },
    { cite: 'Matthew 27:46', text: 'Eli, Eli, lama sabachthani?', gloss: 'that is to say, My God, my God, why hast thou forsaken me?' },
    { cite: 'John 19:28', text: 'I thirst.' },
    { cite: 'John 19:30', text: 'It is finished:', display: 'It is finished.' },
    { cite: 'Luke 23:46', text: 'Father, into thy hands I commend my spirit:', display: 'Father, into thy hands I commend my spirit.' },
  ],
  easter: {
    title: 'Easter Sunday',
    sayings: [
      { cite: 'John 20:21', text: 'Peace be unto you: as my Father hath sent me, even so send I you.' },
      { cite: 'Matthew 28:20', text: 'and, lo, I am with you alway, even unto the end of the world.', display: 'Lo, I am with you alway, even unto the end of the world.' },
    ],
    reflection: 'The first word the risen Jesus gives his friends is peace. The last thing Matthew records him saying is a promise to stay. Forty days are done. The words remain.',
    question: 'Look back over these forty days. What will you carry forward from here?',
  },
  sundayPrompts: [
    'Which saying from this week stayed with you?',
    'Where did you notice God this week?',
    'What do you want to bring into next week?',
  ],
};
