#!/usr/bin/env node
// Writes public/data/safety.js from lib/safety.js so the room hears the same
// phrasings as the server, online and offline. test/safety.test.js fails if
// the two drift.
const fs = require('fs');
const path = require('path');
const { clientBundle } = require('../lib/safety');

function render() {
  return `// Generated by scripts/build-safety.js from lib/safety.js. Do not edit.\nwindow.RLA_SAFETY = ${JSON.stringify(clientBundle(), null, 2)};\n`;
}

if (require.main === module) {
  const dest = path.join(__dirname, '..', 'public', 'data', 'safety.js');
  fs.writeFileSync(dest, render());
  console.log(`wrote ${path.relative(process.cwd(), dest)}`);
}

module.exports = { render };
