#!/usr/bin/env node
// Copies lib/safety-core.js to public/data/safety.js so the room (Carrying,
// the Advisor modal, the offline Advisor) runs the very same code as the
// server. test/safety.test.js fails if the two drift.
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', 'lib', 'safety-core.js');
const DEST = path.join(__dirname, '..', 'public', 'data', 'safety.js');

function render() {
  return '// Generated by scripts/build-safety.js — a verbatim copy of lib/safety-core.js. Do not edit.\n' + fs.readFileSync(SRC, 'utf8');
}

if (require.main === module) {
  fs.writeFileSync(DEST, render());
  console.log(`wrote ${path.relative(process.cwd(), DEST)}`);
}

module.exports = { render };
