#!/usr/bin/env node
/**
 * Derive every static artifact from lib/curated.js, so GitHub Pages ships the
 * same corpus-verified sayings the server does.
 *
 *   public/curated.json      — Today rotation, Seek rooms (with `more`), commons
 *   data/curated.js          — the same object as window.RLA_CURATED
 *   public/data/*.js         — browser copies of data/{curated,letterpress,advisor,paths}.js
 *
 * Usage: node scripts/build-curated.js [--check]
 * --check exits 1 if any artifact on disk differs from what would be written.
 */
const fs = require('fs');
const path = require('path');
const { THEMES, COMMONS, dailyRotation, encouragementFor, themeNames } = require('../lib/curated');

const ROOT = path.join(__dirname, '..');

function curatedObject() {
  const packs = {};
  for (const name of themeNames()) {
    packs[name] = { ...encouragementFor(name), more: THEMES[name].more || [] };
  }
  return { daily: dailyRotation(), packs, commons: COMMONS, translation: 'KJV' };
}

function artifacts() {
  const data = curatedObject();
  const json = JSON.stringify(data, null, 2) + '\n';
  const js = [
    '/* Generated by scripts/build-curated.js from lib/curated.js — do not edit by hand.',
    '   Every quote is KJV text of Jesus, checked against data/spoken-gospels.json in test. */',
    'window.RLA_CURATED = ' + json.trimEnd() + ';',
    '',
  ].join('\n');
  const out = {
    'public/curated.json': json,
    'data/curated.js': js,
    'public/data/curated.js': js,
  };
  for (const name of ['letterpress.js', 'advisor.js', 'paths.js']) {
    out[`public/data/${name}`] = fs.readFileSync(path.join(ROOT, 'data', name), 'utf8');
  }
  return out;
}

function main() {
  const check = process.argv.includes('--check');
  const out = artifacts();
  let stale = 0;
  for (const [rel, content] of Object.entries(out)) {
    const abs = path.join(ROOT, rel);
    const current = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
    if (current === content) continue;
    stale += 1;
    if (check) {
      console.error(`stale: ${rel}`);
    } else {
      fs.mkdirSync(path.dirname(abs), { recursive: true });
      fs.writeFileSync(abs, content);
      console.log(`wrote ${rel}`);
    }
  }
  if (check && stale) {
    console.error(`\n${stale} artifact(s) out of date. Run: npm run curated`);
    process.exit(1);
  }
  if (!stale) console.log('static artifacts are current');
}

if (require.main === module) main();

module.exports = { artifacts, curatedObject };
